### ISSUE TITLE
add support for Junit5

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/flacoco#10]
Flacoco should support Junit5 test for fault localization

Reference: https://github.com/SpoonLabs/astor/issues/307#issuecomment-859341804

**Comment by martinezmatias** [comment]
> Flacoco should support Junit5 test for fault localization

Yes, as  [test-runner](https://github.com/STAMP-project/test-runner) supports junit 4 and 5, that should not be a problem.
I would say that Flacoco, as currently is, supports any test frameworks supported by Test-runner.

**Comment by monperrus** [comment]
great, documented it in 
https://github.com/SpoonLabs/flacoco/commit/f0d1645f8735b61b7dc1d122606f4049eaac47f1

**Comment by andre15silva** [comment]
> great, documented it in [f0d1645](https://github.com/SpoonLabs/flacoco/commit/f0d1645f8735b61b7dc1d122606f4049eaac47f1)

Thanks, I'll improve it in #32
