### ISSUE TITLE
Class files of exampleFL3 not stored in the repo

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/flacoco#11]
Is there any reason why this is the case?

In `exampleFL1` and `exampleFL2`, the class files are in the git repo, but for `exampleFL3` they are computed during CI.

**Comment by martinezmatias** [comment]
Hi @andre15silva 

I'd say that the projects should be compiled by the CI as the case of `exampleFL3 `. 
I do not remember why we have done two different strategies.

I would propose to remove the .class and add two new lines on [.travis.yml](https://github.com/SpoonLabs/flacoco/blob/master/.travis.yml) to build the projects under testing.

**Comment by andre15silva** [comment]
> I'd say that the projects should be compiled by the CI as the case of `exampleFL3 `.

I agree.

> I would propose to remove the .class and add two new lines on [.travis.yml](https://github.com/SpoonLabs/flacoco/blob/master/.travis.yml?rgh-link-date=2021-06-15T14%3A18%3A35Z) to build the projects under testing.

Once we have CI running again, I'll do that (pending https://github.com/SpoonLabs/flacoco/issues/12).

**Comment by martinezmatias** [comment]
great, thanks!
