### ISSUE TITLE
Representation of Results (Flacoco API)

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/flacoco#111]
Flacoco API returns the suspicious data as a Map (see [here](https://github.com/SpoonLabs/flacoco/blob/6c884bfddfdeb867f15a5fd1ff4a51a8fdb5e1d9/src/main/java/fr/spoonlabs/flacoco/localization/spectrum/SpectrumSuspiciousComputation.java#L36))

This means that the client should sort the results.

I think that we can return the results already sorted.

One option, that does not break the API, would be to use to use LinkedHashMap (e.g., [here](https://github.com/SpoonLabs/flacoco/blob/6c884bfddfdeb867f15a5fd1ff4a51a8fdb5e1d9/src/main/java/fr/spoonlabs/flacoco/localization/spectrum/SpectrumSuspiciousComputation.java#L38)).
Another option to change the API and use for instance, SortedMap.

WDYT?

**Comment by andre15silva** [comment]
I've updated the wiki to make it more explicit! (https://github.com/SpoonLabs/flacoco/wiki/API)
