### ISSUE TITLE
Demo issues

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/flacoco#134]
- Not setting the family and formula makes flacoco not output anything
- Usage of the JSON exporter in the API is not working

**Comment by andre15silva** [comment]
On my end:

- flacoco works without setting the family and the formula, assuming the default values.
- the JSON exporter in fact is not working through the API, but works through the CLI (it is not meant to be used like that anyway). I will open an issue for that alone.
- the Spoon results from Math70 are working

I'm working on fixing the remaining issues and will release a new version and give you an example for the demo @dginelli

**Comment by andre15silva** [comment]
@dginelli

I've fixed the log issues (#140, #141), an issue with the formatting of the CLI help message (#136), improved the CSV and JSON output formats to separate class names and line numbers (#139) and released `1.0.1`!

You can find a demo of the API for Math70, using the Spoon results, in this zip:
[flacocodemo.zip](https://github.com/SpoonLabs/flacoco/files/7546503/flacocodemo.zip)

**Comment by dginelli** [comment]
Thank you very much @andre15silva :-)

> flacoco works without setting the family and the formula, assuming the default values.

Probably, when I tried to run Flacoco without setting the family and the formula, I was using the JSON exporter, and so this is why I thought it was necessary to add them to use correctly the Java API.
