### ISSUE TITLE
Question: Running on multiple JUnit versions

### ISSUE THREAD

**Issue by danglotb** [SpoonLabs/flacoco#154]
Hello,

I am asking myself: How do you deal with projects with multiple JUnit versions (3,4,5)?

Thank you very much.

Have a nice day :smile:

**Comment by martinezmatias** [comment]
Hi Ben

Flacoco can receive as parameters two lists of test: one with the JUnit4  (`--junit4tests`)and another with the JUnit5 (`--junit5tests`).   If those arguments are not passed in the command line, Flacoco automatically search for JUnit 4 and JUnit 5 test cases within the project under analysis. Please @andre15silva  correct me if I am wrong.

Regards
Matias

**Comment by danglotb** [comment]
Okay, great. But how Flacoco handles these two lists technically? 

I think that in test-runner, you cannot pass these two lists. Do you make two different runs, one for each version ? (I guess that JUnit3 can be handled with JUnit4).

Thank you for your answer :)

**Comment by andre15silva** [comment]
Hi Benjamin!

> Okay, great. But how Flacoco handles these two lists technically?
> 
> I think that in test-runner, you cannot pass these two lists. Do you make two different runs, one for each version ? (I guess that JUnit3 can be handled with JUnit4).

Yes, flacoco does make two different runs.

It generates a https://github.com/SpoonLabs/flacoco/blob/master/src/main/java/fr/spoonlabs/flacoco/core/test/TestContext.java for each framework. 
Then, we run all of them https://github.com/SpoonLabs/flacoco/blob/2a74fda24c1337280d03ec099fa3722f674ecdee/src/main/java/fr/spoonlabs/flacoco/core/coverage/CoverageRunner.java#L42-L47

**Comment by danglotb** [comment]
Ok thank you very much @andre15silva 

I see now how it is done.

I tried on my side to upgrade with spoon the JUnit test but it is a hard problem when you have Parametrized tests. See [junit-upgrader](https://github.com/davidson-consulting/junit-upgrader)

However, I think that your solution is better.

Closing this issue, thank you very much for your help!
