### ISSUE TITLE
Unable to execute flacoco on Ubuntu 20.04 Terminal

### ISSUE THREAD

**Issue by riteshreddy99** [SpoonLabs/flacoco#167]
![flacoco](https://user-images.githubusercontent.com/32620436/161341868-d5f20332-7932-47eb-bcf2-ae13a38877f2.PNG)

Upon cloning the repository and after successfully running $ mvn install -DskipTests 
When I ran Flacoco on the example math_70 and some other ones it kept showing 
Tests Found and Tests Executed as 0 

Please find the attached screenshot.

Thanks!

**Comment by andre15silva** [comment]
Hi @riteshreddy99 ,

You must install the example projects first, before executing flacoco on them.

Flacoco does not compile the target projects, so they must be compiled beforehand.

Please refer to https://github.com/SpoonLabs/flacoco/wiki#development-environment for further instructions on how to install the example projects

**Comment by riteshreddy99** [comment]
![executing_flacoco](https://user-images.githubusercontent.com/32620436/161384774-57ff3706-a0df-41de-81f0-d9fe0244dcad.PNG)
Hey Andre,

Thanks for the response. I followed what was on the page which was 

export SRC_VERSION=8
./.github/install_examples.sh
mvn test

Upon doing that I ran the command again to execute the tests and it still showed 0. Please take a look at the screenshot

**Comment by andre15silva** [comment]
Sorry, I forgot the script only compiled that project when running on Java 8 (since we use it for test purposes only).

I assume you are not running Java 8, otherwise it should've worked.

Please the following command to compile and test the example project before running flacoco:
```bash
mvn clean test -DskipTests -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8 -B -f examples/math_70/
```

**Comment by riteshreddy99** [comment]
I'm on Java version 11. If I'm not wrong based on what I saw from `java --version`.  
Tried running the command mentioned above. Got a compilation error for that.

![compilation_error](https://user-images.githubusercontent.com/32620436/161385215-ff6afcf8-fa02-4100-bbbd-b72d548899d3.PNG)

**Comment by andre15silva** [comment]
> I'm on Java version 11.

Understood.

> Got a compilation error for that.

That's expected unfortunately.

That example project is not reproducible under that version of Java. 
It comes from the https://github.com/rjust/defects4j dataset, which runs on Java 8.

So, if you want to experiment flacoco you have two options:
- Use a different project which can run on Java 11.
- Switch to Java 8 to run Math70.

If you want to take a look at a smaller scale project which can run on Java 11 please look at the one under `examples/exampleFL1/FLtest1`

**Comment by riteshreddy99** [comment]
As you mentioned I was able to run `examples/exampleFL1/FLtest1` successfully. Could you also please guide me on how to run Flacoco on API as I do not completely understand from the guide. 
The IDE I am using is Eclipse. I've tried importing the project onto Eclipse using Git Clone. But not sure on how to run it

**Comment by andre15silva** [comment]
> Could you also please guide me on how to run Flacoco on API as I do not completely understand from the guide.

Yes!

To use the Flacoco API you must include flacoco as a dependency in your maven project. This means you must add the following to the dependency section of your `pom.xml`:
```
<dependency>
  <groupId>com.github.spoonlabs</groupId>
  <artifactId>flacoco</artifactId>
  <version>1.0.2</version>
</dependency>
```

After that you can just use the API as specified in the wiki.

If you are new to Maven, you can check their docs [here](https://maven.apache.org/guides/getting-started/index.html).
Eclipse probably also has some way of creating a Maven project, but I'm not familiar with that IDE.

**Comment by riteshreddy99** [comment]
Which IDE would you suggest that I could use to run Flacoco?

**Comment by andre15silva** [comment]
> Which IDE would you suggest that I could use to run Flacoco?

Personally I use IntelliJ for development, but keep in mind that this is a personal choice. Eclipse should work should fine.

Flacoco does not depend on any IDE, and running flacoco can be achieved from the terminal.

**Comment by riteshreddy99** [comment]
Hi Andre, I'm trying to test Flacoco with a different dataset with already compiled Java programs how exactly can I test that out? 
https://github.com/jkoppel/QuixBugs
This is the dataset with multiple java programs

**Comment by andre15silva** [comment]
Hi @riteshreddy99 ,

flacoco deploys Spectrum-Based Fault Localization (SBFL), a technique which makes use of a test suite (with failing and passing test cases) to identify suspicious lines of code w.r.t. the fault.

Additionally, flacoco only supports JUnit tests so you would need to use the following tests: https://github.com/jkoppel/QuixBugs/tree/master/java_testcases/junit

If you are using Java through the CLI you could set the options `--binJavaDir` and `--binTestDir` pointing to the top-level directory of where the binaries can be found.

If using through the API, you can use the `setBinJavaDir` and `setBinTestDir` options in your `FlacocoConfig` to do the same.

**Comment by riteshreddy99** [comment]
Hey Andre,

Thanks again for the response. As per what you mentioned above I tried running the command using those parameters but I'm not able to execute the tests.
![Quixxbiga](https://user-images.githubusercontent.com/32620436/161963899-7c28cb95-7322-47f5-9568-114e4a19a16b.PNG)

Thank you.

**Comment by andre15silva** [comment]
> Thanks again for the response. As per what you mentioned above I tried running the command using those parameters but I'm not able to execute the tests. Quixxbugs mentions that the java programs are already compiled ![Quixxbiga](https://user-images.githubusercontent.com/32620436/161963899-7c28cb95-7322-47f5-9568-114e4a19a16b.PNG)

Could you show me the contents of both the directories you set as `binJavaDir` and `binTestDir`?

**Comment by riteshreddy99** [comment]
Please find the attached screenshot and the link to the repository 
[https://github.com/jkoppel/QuixBugs](url) 
It would be great if you could type out the command that I could use to test it out. Thanks!
![junit](https://user-images.githubusercontent.com/32620436/162036887-b7d3dbad-252a-41b0-b1e2-4776b9f62f63.PNG)
![javap](https://user-images.githubusercontent.com/32620436/162037300-c711e1bc-0778-429f-ade0-10086c8567cd.PNG)

**Comment by andre15silva** [comment]
Hi @riteshreddy99 ,

Two things:
- The tests are not compiled, so you must compile them first.
- The binaries must be stored in the normal java fashion. This means that you should have two directories for each example:
  - One where you keep the source code binaries
  - One where you keep the test binaries
  - You then select these directories as, respectively, the `binJavaDir` and `binTestDir` options

**Comment by andre15silva** [comment]
Hi @riteshreddy99 

I'm not able to provide support for GZoltar sorry. 

I'd suggest you open an issue in https://github.com/GZoltar/gzoltar's repo.

**Comment by andre15silva** [comment]
Hi @riteshreddy99 

For IntroClassJava it is easier.

You can just go to a bug, for instance https://github.com/Spirals-Team/IntroClassJava/tree/master/dataset/checksum/08c7ea4ac39aa6a5ab206393bb4412de9d2c365ecdda9c1b391be963c1811014ed23d2722d7433b8e8a95305eee314d39da4950f31e01f9147f90af91a5c433a/006, and run:

```bash
cd "<path_to_bug>"
mvn test
java -jar "<path_to_flacoco_jar>" --projectPath ./
```

It should work like that, as they are Maven projects and flacoco assumes the Maven project structure as default.

**Comment by riteshreddy99** [comment]
Yes! it is working. It seems to be working without running `mvn test` is that okay?
Instead directly running this command `java -jar "<path_to_flacoco_jar>" --projectPath ./`
![introjava](https://user-images.githubusercontent.com/32620436/163148201-15808bf1-3b24-48b0-b543-6a73ba9ecb37.PNG)

**Comment by riteshreddy99** [comment]
I plan to invoke Flacoco through a simple Java Application GUI is that possible?

**Comment by andre15silva** [comment]
Hi @riteshreddy99 ,

Flacoco does not provide a GUI.

You can program a GUI that calls Flacoco, but that's out of the scope of our work here.
