### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/flacoco#174]
Hi @andre15silva 
Can we release the new version to maven central? (version 1.0.3).
Thanks
Regards
Matias

**Comment by andre15silva** [comment]
Hi @martinezmatias 

Of course!

We should probably merge #169 and #173 first tho

**Comment by andre15silva** [comment]
@martinezmatias I have release `1.0.3` which includes Java 17 support.

For some reason Java 18 bytecode is leading to timeout exceptions. I'm further investigating in #176

**Comment by martinezmatias** [comment]
Hi @andre15silva 

>  I have released 1.0.3 which includes Java 17 support.

Great, thanks

> For some reason Java 18 bytecode is leading to timeout exceptions. I'm further investigating

Ok!

**Comment by monperrus** [comment]
:+1:

**Comment by monperrus** [comment]
Nopol bumped to 1.0.3: https://github.com/SpoonLabs/nopol/pull/227
