### ISSUE TITLE
Possibly wrong plugin

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/flacoco#18]
https://github.com/SpoonLabs/flacoco/blob/5b277749de11968be96708ecb37a5e45e7ee6016/pom.xml#L64-L85

I don't understand this plugin. What is the purpose of it?

**Comment by martinezmatias** [comment]
Hi @andre15silva 

It's for creating a "fat" jar which includes all the dependencies of the project.

**Comment by andre15silva** [comment]
> It's for creating a "fat" jar which includes all the dependencies of the project.

But what does Astor have to do with this?

**Comment by martinezmatias** [comment]
> But what does Astor have to do with this?

https://github.com/SpoonLabs/flacoco/blob/5b277749de11968be96708ecb37a5e45e7ee6016/pom.xml#L69

that is caused by an ugly copy and paste.

**Comment by martinezmatias** [comment]
I'd keep the plugin, but change the value of that tag.
