### ISSUE TITLE
WARN TestMethodFilter - NoClassDefFoundError

### ISSUE THREAD

**Issue by FoxMakarov** [SpoonLabs/flacoco#185]
Hi. When using the Flacoco project to analyze Closure project in the defects4j dataset, use closure_2_ buggy for example, because the file structure in this project is different from the default structure mentioned in the FlacocoMain.java file, I give "-- srcJavaDir", "srcTestDir", "binTestDir" and "binJavaDir" as arguments in the flacoco command line to indicate the location. 
The version of defects4j is version 2.0.0. The JDK version is 1.8.0_45.
The closure_2_buggy is checkout from Defects4j with the instruction “defects4j checkout -p Closure -v 2b -w /home/arka/SLPRFL/Tests/defects4j/Closure/closure_2_buggy”，and The “binTestDir” and “binJavaDir” are generated by this instruction”defects4j test”.

There are two questions:
- Many tests not reported by test-runner. In closure_2_buggy, only 833 tests are executed while total number of tests is 9949.
- Many file , “SourceMapConsumerFactory.java” for example, exist in srcJavaDir and binJavaDir, but NoClassDefFoundError.

![J$9D(JS)`DJSL{72%WET`OB](https://user-images.githubusercontent.com/58101484/168006099-5211b3eb-f0db-4c82-8a7a-319f49daa613.png)
![NTJX6 0V1%4 5)GPJ3Z`1 S](https://user-images.githubusercontent.com/58101484/168006204-028f0084-6a37-4edb-88b3-94bb3ce3a81e.png)

I saw the first question has been reported by others in issue 179. I want to know what caused the second problem. Is there something wrong with my compilation？Is there any bad influence here? I'm not very familiar with this.

Thanks!

**Comment by martinezmatias** [comment]
Hi @FoxMakarov 

We suspect that it could be an issue on the command line that you attached: It could not find the `classpath` parameter ([See here](https://github.com/SpoonLabs/flacoco/blob/master/src/main/java/fr/spoonlabs/flacoco/cli/FlacocoMain.java#L39), which allows to specify the classpath of the project under analysis). 
Consequently, both issues you mention could be related to that.
Regards
Matias

**Comment by FoxMakarov** [comment]
Thanks for your reply!

Taking "WARN TestMethodFilter - NoClassDefFoundError: class com.google.debugging.sourcemap.SourceMapConsumerFactory" for example, I try to add the location of "SourceMapConsumerFactory.class" after this parameter "--classpath". I think that specifying classpath as the directory of this file may cause other errors, but this file should be found. But in fact, it couldn't be found.

I'm confused about this. 
![XHMC__DKFBSIR$4}83UVTUA](https://user-images.githubusercontent.com/58101484/171576966-db2e6281-9e05-4ca5-8ef7-960f7c0baec6.png)

**Comment by FoxMakarov** [comment]
Thanks for your teaching!
