### ISSUE TITLE
Test found 0, Tests executed 0 

### ISSUE THREAD

**Issue by ssk1216** [SpoonLabs/flacoco#197]
The following command  : java -jar target/flacoco-1.0.6-SNAPSHOT-jar-with-dependencies.jar -p  examples/exampleFL1/FLtest1

dislays the below text.  
[0] INFO Flacoco - Running Flacoco...
[32] INFO CoverageRunner - Tests found: 0
[32] INFO CoverageRunner - Tests executed: 0

Why do I get this error?

**Comment by andre15silva** [comment]
Hi @ssk1216 ,

Did you compile the project you are trying to execute before executing flacoco on it?

I'm asking this because flacoco does do any compilation, therefore, you must provide an already compiled project.

I suggest you run `mvn test -DskipTests` so that you compile both source and test classes.

**Comment by ssk1216** [comment]
@andre15silva ,  Thanks.  Is it mandatory that the projects to be tested should be maven projects? How about if it is a  X.java and XTest.java. (java source and its associated test class)?

**Comment by andre15silva** [comment]
> Is it mandatory that the projects to be tested should be maven projects? How about if it is a X.java and XTest.java. (java source and its associated test class)?

No, there is no requirement for it to be a Maven project.

However, if you only specify the parameter `--projectpath` or `-p` for short, flacoco will assume the Maven project structure as default.

You can override this by defining your own paths:
```
      --binJavaDir[=<binJavaDir>...]
                            Paths to the directories containing java class
                              files. Defaults to {projectpath}/target/classes
      --binTestDir[=<binTestDir>...]
                            Paths to the directories containing java test class
                              files. Defaults to {projectpath}
                              /target/test-classes
      --srcJavaDir[=<srcJavaDir>...]
                            Paths to the directories containing java source
                              files. Defaults to {projectpath}/src/main/java
      --srcTestDir[=<srcTestDir>...]
                            Paths to the directories containing java test
                              source files. Defaults to {projectpath}/src/test
```

Full reference: https://github.com/SpoonLabs/flacoco/wiki/CLI or just use the `--help` option
