### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/flacoco#26]
Right now, the test suite fails when running on both these OSs

**Comment by martinezmatias** [comment]
Hi @andre15silva 

> Right now, the test suite fails when running on both these OSs

Strange. Do you have the link to the log?

Thanks
Regards
Matias

**Comment by andre15silva** [comment]
Hi @martinezmatias 

Seems like it's only Windows actually. MacOS was failing but because it was canceled, my bad.

[Failing build](https://github.com/andre15silva/flacoco/runs/2882708508?check_suite_focus=true)

It as something to do with the paths to the example projects, so it probably isn't anything complicated.

**Comment by martinezmatias** [comment]
> It as something to do with the paths to the example projects

Right, It could be related to that.
