### ISSUE TITLE
Include lines that throw exceptions in coverage

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/flacoco#33]
Flacoco does not well treat the cases when the cases throws an exception.

**Comment by andre15silva** [comment]
What do you mean by "does not treat well"?

I thought that was at least partially working, as this test shows:

https://github.com/SpoonLabs/flacoco/blob/c9185951418554b5c44f647145256afb0169b7c5/src/test/java/fr/spoonlabs/flacoco/api/FlacocoTest.java#L72-L108

The only issue I see is that the line where the actual exception is thrown is not included in the coverage computation.

**Comment by martinezmatias** [comment]
> The only issue I see is that the line where the actual exception is thrown is not included in the coverage computation. 

Exact.

If we have the bug:

```
10 Integer i = null;
11 i.toString();
```

Then, line 11, which is the buggy, will not be included in the suspicious list.

**Comment by andre15silva** [comment]
```
Source code lines with exceptions show no coverage. Why?

JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding line of source code is not marked as covered. 
```

https://www.jacoco.org/jacoco/trunk/doc/faq.html

**Comment by martinezmatias** [comment]
Hi @andre15silva 

Do you have in mind any strategy to apply here? 

We would need to post process the list of suspiciousness. We can mark the locations that are part of the a stack trace.

**Comment by andre15silva** [comment]
> Hi @andre15silva

Hi @martinezmatias 

> Do you have in mind any strategy to apply here?

Not yet.

> We would need to post process the list of suspiciousness. We can mark the locations that are part of the a stack trace.

That's a good idea, and if I'm not mistaken `test-runner` already returns this information.

**Comment by martinezmatias** [comment]
Hi @andre15silva 

>  if I'm not mistaken test-runner already returns this information
That would be nice. 

Coming back to the example I wrote before, I mentioned that the buggy line is the 11. That is not always true, as the problem is the variable 'i' was not initialized and it should be done before executing line 11. Even line 11 is not in the suspicious list, that list will contain statements that could be modified to fix the bug (e.g., line 10, or adding a new statement after line 10 that initializes de var)

**Comment by andre15silva** [comment]
Hi @martinezmatias 

> Coming back to the example I wrote before, I mentioned that the buggy line is the 11. That is not always true, as the problem is the variable 'i' was not initialized and it should be done before executing line 11. Even line 11 is not in the suspicious list, that list will contain statements that could be modified to fix the bug (e.g., line 10, or adding a new statement after line 10 that initializes de var)

Yes, I understood. It's just another suspicious line.
