### ISSUE TITLE
Automated selection of test runner

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/flacoco#34]
Flacoco should be able to automatically select, given a project P given as input, the test runner according to the test framework used by P

**Comment by andre15silva** [comment]
I agree.

We could do this at least in the following two ways:

- Identify through the given classpath
- Identify through the `pom.xml` of the project

**Comment by martinezmatias** [comment]
Another way could be: (as far I remember I implemented it somewhere, I'll find it).
* Determine automatically the framework by analyzing the tests.
** From the `test-runner` we have access to the different test-frameworks.
** For each test framework F we call the method to retrieve test related to F.
** We finally select the F with largest amount of test cases (In most of the cases it will be a single test framework).

Actually, we can combine different heuristics: we can start analyzing the pom or the dependency tree (but it could have several test libraries), then, if we find more than 2 test libs,  we proceed the aforementioned heuristic.

WDYT?

**Comment by andre15silva** [comment]
>       ** We finally select the F with largest amount of test cases (In most of the cases it will be a single test framework).

We could even run all `test-runner` compatible tests and combine the results.

> Actually, we can combine different heuristics: we can start analyzing the pom or the dependency tree (but it could have several test libraries), then, if we find more than 2 test libs, we proceed the aforementioned heuristic.
> 
> WDYT?

That sounds good yes.
