### ISSUE TITLE
Enable github wiki

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/flacoco#37]
I seem to lack the permission to initialize the wiki.

It would be nice to have some extensive and structured documentation, instead of just putting everything in the README.

**Comment by martinezmatias** [comment]
> I seem to lack the permission to initialize the wiki.

Enabled. There is an checkbox on Settings-> Options -> Features ->wiki, which was disable.

https://github.com/SpoonLabs/flacoco/wiki

**Comment by andre15silva** [comment]
Thanks @martinezmatias !
