### ISSUE TITLE
Performance optimization and scalability

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/flacoco#4]
The idea is to reduce the performance by minimizing the numbers of time we invoke Test-runner + instrumentation.

**Comment by monperrus** [comment]
One requirement is that Flacoco has to be as fast as GZoltar.

**Comment by andre15silva** [comment]
To do this, we should move our `test-runner` usage to its `EntryPoint` and implement the required changes in `test-runner` too.

**Comment by martinezmatias** [comment]
Hi @andre15silva 

> To do this, we should move our test-runner usage to its EntryPoint and implement the required changes in test-runner too.

Could you put the link to the code you propose to move to `test-runner` project?


The main issue IMO is we call `test-runner` for each test method:
https://github.com/SpoonLabs/flacoco/blob/master/src/main/java/fr/spoonlabs/flacoco/core/coverage/CoverageRunner.java#L55

And way  creates an important overhead. However, using JaCoCo, it could not obtain the which (test) method calls each covered line.

**Comment by andre15silva** [comment]
> Hi @andre15silva

Hi @martinezmatias 

> Could you put the link to the code you propose to move to `test-runner` project?
> 
> The main issue IMO is we call `test-runner` for each test method:
> [`master`/src/main/java/fr/spoonlabs/flacoco/core/coverage/CoverageRunner.java#L55](https://github.com/SpoonLabs/flacoco/blob/master/src/main/java/fr/spoonlabs/flacoco/core/coverage/CoverageRunner.java?rgh-link-date=2021-06-22T13%3A04%3A32Z#L55)
>
> And way creates an important overhead. However, using JaCoCo, it could not obtain the which (test) method calls each covered line.

Right now we do it here https://github.com/SpoonLabs/flacoco/blob/36226f201623a1cbdeffc6691bfe35512799d0fb/src/main/java/fr/spoonlabs/flacoco/core/coverage/CoverageRunner.java#L41-L71

My idea is to implement an API in https://github.com/STAMP-project/test-runner/blob/master/src/main/java/eu/stamp_project/testrunner/EntryPoint.java#, for several reasons:

- This is the recommended way to run `test-runner`
- By using it, the tests will run in a separate JVM, which has several advantages (e.g. reliability, configurations)
- It is cleaner and simpler from `flacoco`'s side
- It makes this specific usage of `test-runner` available to its other users

About the issue with JaCoCo, I think `test-runner`, through its [`CoveragePerTestMethod` API](https://github.com/STAMP-project/test-runner/blob/3541dd9a5bf4f7ef50a85ec2536ff384a12fcf30/src/main/java/eu/stamp_project/testrunner/EntryPoint.java#L364-L388) in the `EntryPoint` already does that.

So, if I'm correct, we only need to link the two types of information, `TestResult` and `Coverage` and return it.

**Comment by martinezmatias** [comment]
> My idea is to implement an API in https://github.com/STAMP-project/test-runner/blob/master/src/main/java/eu/stamp_project/testrunner/EntryPoint.java#

Perfect. Go ahead. I agree with the reasons you wrote. 

> By using it, the tests will run in a separate JVM, which has several advantages (e.g. reliability, configurations)

Completely agree.

> if I'm correct, we only need to link the two types of information, TestResult and Coverage and return it.

Does the entity `CoveredTestResult ` do that link?

**Comment by andre15silva** [comment]
> Does the entity `CoveredTestResult ` do that link?

That's what we do currently, but I'm not sure it will work for `CoveragePerTest`. I need to dig a bit more into `test-runner` to understand what the best option is.

**Comment by martinezmatias** [comment]
>  I need to dig a bit more into test-runner to understand what the best option is.

okay!

**Comment by andre15silva** [comment]
FYI, https://github.com/STAMP-project/test-runner/pull/95 is the PR associated with this issue.

**Comment by andre15silva** [comment]
STAMP-project/test-runner#95 introduces one optimization, which enables us to run all test methods from a test class together. 

The issue after that is that we ideally want to run all test classes along all its test methods in one go, but `test-runner` does not quite support this well (see https://github.com/STAMP-project/test-runner/issues/86)
