### ISSUE TITLE
Reporting results

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/flacoco#44]
when we use Flacoco in command line via the jar, the results are printed in the standard output.
It would be nice to:

- [x] add an option to export the results (i.e., list of statements + suspicious value) to CSV (Closed by #47).
- [x] (less relevant) add an extension point to plug code that exports code to other format.

**Comment by andre15silva** [comment]
For the second point, we could have an option which allows loading a `FlacocoExporter` in runtime.

WDYT?

**Comment by martinezmatias** [comment]
> For the second point, we could have an option which allows loading a FlacocoExporter in runtime.

Exact. We can use reflexion. So, we can add a new entry in the Forman enum, that can be `CUSTOM` and a new argument to pass the class name to be loaded.

**Comment by andre15silva** [comment]
> Exact. We can use reflexion. So, we can add a new entry in the Forman enum, that can be `CUSTOM`, and a new argument to pass the class name (which must implement FlacocoExporter) to be loaded.

Okay. I'll add this feature to #47 then.
