### ISSUE TITLE
Detailed Suspiciousness result

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/flacoco#54]
https://github.com/SpoonLabs/astor requires more information than the one currently provided through the FlacocoAPI. For example, which failing test cases cover a certain suspicious line.

My suggestion is that we change the API results from `Map<?, Double>` to `Map<?, SuspiciousnessInformation>`, where `SuspiciousnessInformation` would contain all the information such as the score, failing test cases, passing test cases, etc.

**Comment by martinezmatias** [comment]
Hi @andre15silva 

> https://github.com/SpoonLabs/astor requires more information than the one currently provided through the FlacocoAPI. For example, which failing test cases cover a certain suspicious line.

Ok, I didn't remember about that.

> My suggestion is that we change the API results from Map<?, Double> to Map<?, SuspiciousnessInformation>, where SuspiciousnessInformation would contain all the information such as the score, failing test cases, passing test cases, e

It makes perfectly sense for me.

Regards
Matias
