### ISSUE TITLE
Different results compared to GZoltar

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/flacoco#62]
Running on https://github.com/SpoonLabs/astor/tree/master/examples/quixbugscompiled/depth_first_search.

`flacoco`:

>         Candidate [className=java_programs.Node, methodName=null, lineNumber=51, susp=1.0], 
>         Candidate [className=java_programs.Node, methodName=null, lineNumber=50, susp=1.0], 
>         Candidate [className=java_programs.DEPTH_FIRST_SEARCH$1Search, methodName=null, lineNumber=22, susp=0.5], 
>         Candidate [className=java_programs.Node, methodName=null, lineNumber=62, susp=0.5], 
>         Candidate [className=java_programs.DEPTH_FIRST_SEARCH, methodName=null, lineNumber=14, susp=0.4472135954999579], 
>         Candidate [className=java_programs.DEPTH_FIRST_SEARCH$1Search, methodName=null, lineNumber=17, susp=0.4472135954999579], 
>         Candidate [className=java_programs.DEPTH_FIRST_SEARCH$1Search, methodName=null, lineNumber=15, susp=0.4472135954999579], 
>         Candidate [className=java_programs.DEPTH_FIRST_SEARCH, methodName=null, lineNumber=30, susp=0.4472135954999579], 
>         Candidate [className=java_programs.DEPTH_FIRST_SEARCH$1Search, methodName=null, lineNumber=19, susp=0.4472135954999579], 
>         Candidate [className=java_programs.DEPTH_FIRST_SEARCH, methodName=null, lineNumber=12, susp=0.4472135954999579]], 
> 		  failingTestCases=[java_testcases.DEPTH_FIRST_SEARCH_TEST]}

To run separate from `astor`, replace the paths accordingly in the following command:
`java -jar target/flacoco-0.0.1-SNAPSHOT-jar-with-dependencies.jar --testRunnerVerbose -v --projectpath /home/andre/Repos/astor/examples/quixbugs/depth_first_search/ --srcJavaDir=/home/andre/Repos/astor/examples/quixbugs/depth_first_search/src/ --srcTestDir=/home/andre/Repos/astor/examples/quixbugs/depth_first_search/src/ --binJavaDir=/home/andre/Repos/astor/examples/quixbugscompiled/depth_first_search/bin/ --binTestDir=/home/andre/Repos/astor/examples/quixbugscompiled/depth_first_search/bin/`

`gzoltar`:

>     Candidate [className=java_programs.Node, methodName=setSuccessors(Ljava/util/ArrayList;)V, lineNumber=50, susp=1.0], 
>     Candidate [className=java_programs.Node, methodName=setSuccessors(Ljava/util/ArrayList;)V, lineNumber=51, susp=1.0], 
>     Candidate [className=java_programs.DEPTH_FIRST_SEARCH$1Search, methodName=search(Ljava_programs/Node;)Z, lineNumber=23, susp=0.5773502691896258], 
>     Candidate [className=java_programs.DEPTH_FIRST_SEARCH$1Search, methodName=search(Ljava_programs/Node;)Z, lineNumber=22, susp=0.5], 
>     Candidate [className=java_programs.Node, methodName=getSuccessors()Ljava/util/ArrayList;, lineNumber=62, susp=0.5], 
>     Candidate [className=java_programs.DEPTH_FIRST_SEARCH$1Search, methodName=search(Ljava_programs/Node;)Z, lineNumber=17, susp=0.4472135954999579], 
>     Candidate [className=java_programs.DEPTH_FIRST_SEARCH$1Search, methodName=search(Ljava_programs/Node;)Z, lineNumber=19, susp=0.4472135954999579], 
>     Candidate [className=java_programs.DEPTH_FIRST_SEARCH, methodName=depth_first_search(Ljava_programs/Node;Ljava_programs/Node;)Z, lineNumber=14, susp=0.4472135954999579], 
>     Candidate [className=java_programs.DEPTH_FIRST_SEARCH, methodName=depth_first_search(Ljava_programs/Node;Ljava_programs/Node;)Z, lineNumber=30, susp=0.4472135954999579], 
>     Candidate [className=java_programs.DEPTH_FIRST_SEARCH, methodName=depth_first_search(Ljava_programs/Node;Ljava_programs/Node;)Z, lineNumber=31, susp=0.4472135954999579]], 
> 	  failingTestCases=[java_testcases.DEPTH_FIRST_SEARCH_TEST]}

Output from `astor`.

The differences are:
- GZoltar identified line 23 of `java_programs.DEPTH_FIRST_SEARCH$1Search`, but flacoco didn't
- flacoco identified line 15 of `java_programs.DEPTH_FIRST_SEARCH$1Search`, but GZoltar didn't
- GZoltar identified line 31 of `java_programs.DEPTH_FIRST_SEARCH$1Search`, but flacoco didn't

**Comment by monperrus** [comment]
See https://github.com/SpoonLabs/flacoco/issues/103#issuecomment-933036892 for Math 78

**Comment by monperrus** [comment]
And https://github.com/SpoonLabs/flacoco/issues/104#issuecomment-933036104 for Math 84
