### ISSUE TITLE
Option for tests to run

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/flacoco#65]
In https://github.com/SpoonLabs/astor, the tests to run are computed before running the entire flacoco "pipeline".

In order to save time, we should allow tests to be specified through an option such that test detection would be bypassed.

**Comment by martinezmatias** [comment]
Hi @andre15silva 
Any more detail about this issue?
Thanks :)
Matias

**Comment by andre15silva** [comment]
Hi @martinezmatias ,

Sorry, I opened it so I wouldn't forget today. Updated the comment above.

**Comment by martinezmatias** [comment]
Hi @andre15silva , No problem :)
