### ISSUE TITLE
Detecting `lang63` tests

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/flacoco#71]
Test detection faces a bug in the `lang63` example, because of the following test cases:

```
org.apache.commons.lang.enum.EnumTest
org.apache.commons.lang.enum.EnumUtilsTest
org.apache.commons.lang.enum.ValuedEnumTest
```

The issue is that the fully qualified names passed to `test-runner`, for these classes, are actually just the class name itself:

> [EnumTest, EnumUtilsTest, ValuedEnumTest, org.apache.commons.lang.ArrayUtilsAddTest, org.apache.commons.lang.ArrayUtilsRemoveTest, org.apache.commons.lang.ArrayUtilsTest, org.apache.commons.lang.BitFieldTest, org.apache.commons.lang.BooleanUtilsTest, org.apache.commons.lang.CharEncodingTest, org.apache.commons.lang.CharRangeTest, ...

My working hypothesis is that this issue comes from Spoon not handling a package name with the keyword `enum` well.

**Comment by martinezmatias** [comment]
Hi @andre15silva 

> My working hypothesis is that this issue comes from Spoon not handling a package name with the keyword enum well.

Good point. Probably the problem is that one you mentioned.
FYI: In Astor, when we create the Spoon model, we pass as parameter the java compliance level. I remember that the level for some Defects4J 's bug was 4 , thus `enum` was allowed to be used.

**Comment by andre15silva** [comment]
Hi @martinezmatias 

It is the same case yes:

`as of release 5, 'enum' is a keyword, and may not be used as an identifier`

PR coming soon to include an option for the compliance level and better handle test detection.

**Comment by martinezmatias** [comment]
> PR coming soon to include an option for the compliance level and better handle test detection.

Perfect. It makes sense. If there user does not pass as argument a compliance level we have two options: a) set a default value that we set (e.g., 8), b) don't pass nothing to Spoon, so it will use the default level from Spoon.

**Comment by andre15silva** [comment]
https://github.com/INRIA/spoon/pull/4068 fixes this issue.
