### ISSUE TITLE
How to use flacoco?

### ISSUE THREAD

**Issue by jose** [SpoonLabs/flacoco#8]
Hi @martinezmatias and @monperrus,

I've just come across your fault localization tool flacoco and I would like to try it.  Could you please provide some instructions on how should one use it?

--
Best,
Jose

**Comment by martinezmatias** [comment]
Hi @jose 

Thanks for your interest on Flacoco.
I'll prepare a detailed document. 

We plan to resume the projects very soon, so new changes and features -and docs as well- will be introduced.

Regards
Matias

**Comment by jose** [comment]
Great, thanks.

**Comment by martinezmatias** [comment]
Hi @jose 

We now have a well documented readme and wiki (done by @andre15silva)

if you have any question about the usage, please, don't hesitate to write us.

Regards
Matias

**Comment by jose** [comment]
Thanks.  I will give it a try later.
