### ISSUE TITLE
Test detection missing tests

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/flacoco#80]
On `math70`, we are only detecting and running 1676 tests out of the 2181 available.

**Comment by martinezmatias** [comment]
Hi @andre15silva 

Does https://github.com/SpoonLabs/flacoco/pull/79 fix this issue? 

Should we add an assertion (which controls nr of test == 2181) in test [Math70Test.java]?(https://github.com/SpoonLabs/flacoco/blob/master/src/test/java/fr/spoonlabs/flacoco/api/Math70Test.java#L39)

**Comment by andre15silva** [comment]
Hi @martinezmatias

No, it doesn't.

I already did here https://github.com/SpoonLabs/flacoco/blob/14585dd66c87265e2b3379ae6302076d76b82891/src/test/java/fr/spoonlabs/flacoco/core/test/TestDetectorTest.java#L385-L407

**Comment by andre15silva** [comment]
These are test suites, and don't contain unit tests.

GZoltar considers them, and will consider duplicated test results in the end

> [42865] INFO GZoltarFaultLocalization - Test failt: org.jfree.chart.util.junit.ShapeUtilitiesTests#testEqualGeneralPaths
[42867] INFO GZoltarFaultLocalization - Test failt: org.jfree.chart.util.junit.ShapeUtilitiesTests#testEqualGeneralPaths
