### ISSUE TITLE
Simplify output

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/flacoco#88]
Right now we return a mapping between a string representation and a `Suspiciousness` value.

We might want to simplify this representation, as well as make it easier to obtain the class name, line number, etc.

This should be done before we do our first release too.

**Comment by martinezmatias** [comment]
Hi @andre15silva 

Perfect. I agree that this is a necessary change in order facilitate interpretation of the results.
We can also create extension points to decide which information it should export.
