### ISSUE TITLE
add support for linking to Spoon elements

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/flacoco#9]
in many of our downstream projects, we need to link fault localization information to Spoon elements, it would make sense to have it here.

**Comment by martinezmatias** [comment]
In Astor, the code for linking the output of FL with Spoon elements is [here](https://github.com/SpoonLabs/astor/blob/bcc8463eeb00545f921f9216be694807014263ea/src/main/java/fr/inria/astor/core/faultlocalization/bridgeFLSpoon/SpoonLocationPointerLauncher.java#L21)
